#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPEmailProperty.h"
#import "ASPLink.h"


@protocol ASPEmailProperties
@end

@interface ASPEmailProperties : ASPObject


@property(nonatomic) ASPLink* link;

@property(nonatomic) NSArray<ASPEmailProperty>* list;

@end
