#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPObject.h"


@protocol ASPStream
@end

@interface ASPStream : ASPObject


@property(nonatomic) ASPObject* identity;

@end
