<?php
namespace Aspose\Email\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class EmailPropertyResponse {
	static $swaggerTypes = array(
		'EmailProperty' => 'EmailProperty',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $EmailProperty; // EmailProperty
	public $Code; // string
	public $Status; // string
	}

