<?php
namespace Aspose\Email\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class EmailProperty {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'Name' => 'string',
		'Value' => 'object'

	);

	public $Link; // Link
	public $Name; // string
	public $Value; // object
	}

