<?php
namespace Aspose\Email\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class EmailDocument {
	static $swaggerTypes = array(
		'Links' => 'array[Link]',
		'DocumentProperties' => 'EmailProperties',
		'Data' => 'System.IO.Stream',
		'Format' => 'string'

	);

	public $Links; // array[Link]
	public $DocumentProperties; // EmailProperties
	public $Data; // System.IO.Stream
	public $Format; // string
	}

