<?php
namespace Aspose\Email\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class EmailProperties {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'List' => 'array[EmailProperty]'

	);

	public $Link; // Link
	public $List; // array[EmailProperty]
	}

