#import <Foundation/Foundation.h>
#import "ASPEmailDocument.h"
#import "ASPEmailDocumentResponse.h"
#import "ASPEmailProperty.h"
#import "ASPEmailPropertyResponse.h"
#import "ASPEmailDocumentWithStringValue.h"
#import "ASPObject.h"
#import "ASPApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface ASPEmailApi: NSObject

@property(nonatomic, assign)ASPApiClient *apiClient;

-(instancetype) initWithApiClient:(ASPApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(ASPEmailApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;

///
///
/// Get mail common info.
///
///
/// @param name File name.
/// @param storage The document storage.
/// @param folder Folder path.
///
///
/// @return NSURL*
-(NSNumber*) getDocumentWithCompletionBlock :(NSString*) name
                                     storage:(NSString*) storage
                                      folder:(NSString*) folder

                           completionHandler: (void (^)(NSURL* output, NSError* error))completionBlock;



///
///
/// Get mail in specified format
///
///
/// @param name File name.
/// @param format
/// @param outPath
/// @param storage The document storage.
/// @param folder Folder path.
///
///
/// @return NSURL*
-(NSNumber*) getDocumentWithFormatWithCompletionBlock :(NSString*) name
                                                format:(NSString*) format
                                               outPath:(NSString*) outPath
                                               storage:(NSString*) storage
                                                folder:(NSString*) folder 

                                     completionHandler: (void (^)(NSURL* output, NSError* error))completionBlock;

///
///
/// Add new email.
/// 
///
/// @param name The email name.
/// @param email Email data.
/// @param storage The document storage.
/// @param folder The email folder.
/// 
///
/// @return ASPEmailDocumentResponse*
-(NSNumber*) putCreateNewEmailWithCompletionBlock :(NSString*) name 
     email:(ASPEmailDocumentWithStringValue*) email 
     storage:(NSString*) storage 
     folder:(NSString*) folder 
    
    completionHandler: (void (^)(ASPEmailDocumentResponse* output, NSError* error))completionBlock;
    


///
///
/// Get email attachment by name.
/// 
///
/// @param name The email message name.
/// @param attachName Attachment name.
/// @param storage Message storage.
/// @param folder Message folder.
/// 
///
/// @return NSURL*
-(NSNumber*) getEmailAttachmentWithCompletionBlock :(NSString*) name 
     attachName:(NSString*) attachName 
     storage:(NSString*) storage 
     folder:(NSString*) folder 
    
    completionHandler: (void (^)(NSURL* output, NSError* error))completionBlock;
    


///
///
/// Add email attachment.
/// 
///
/// @param name Email name.
/// @param attachName Attachment path.
/// @param storage Email&#39;s storage.
/// @param folder Email&#39;s folder.
/// 
///
/// @return ASPEmailDocumentResponse*
-(NSNumber*) postAddEmailAttachmentWithCompletionBlock :(NSString*) name 
     attachName:(NSString*) attachName 
     storage:(NSString*) storage 
     folder:(NSString*) folder 
    
    completionHandler: (void (^)(ASPEmailDocumentResponse* output, NSError* error))completionBlock;
    


///
///
/// Read document property by name.
///
///
/// @param propertyName Name of document property
/// @param name File name
/// @param storage The document storage.
/// @param folder Folder path
///
///
/// @return ASPEmailPropertyResponse*
-(NSNumber*) getEmailPropertyWithCompletionBlock :(NSString*) propertyName
                                             name:(NSString*) name
                                          storage:(NSString*) storage
                                           folder:(NSString*) folder

                                completionHandler: (void (^)(ASPEmailPropertyResponse* output, NSError* error))completionBlock;
    


///
///
/// Set document property.
/// 
///
/// @param name 
/// @param propertyName 
/// @param _property 
/// @param storage 
/// @param folder 
/// 
///
/// @return ASPEmailPropertyResponse*
-(NSNumber*) putSetEmailPropertyWithCompletionBlock :(NSString*) name 
     propertyName:(NSString*) propertyName 
     _property:(ASPEmailPropertyWithStringValue*) _property
     storage:(NSString*) storage 
     folder:(NSString*) folder 
    
    completionHandler: (void (^)(ASPEmailPropertyResponse* output, NSError* error))completionBlock;
    



@end
