#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPEmailProperty
@end

@interface ASPEmailProperty : ASPObject


@property(nonatomic) ASPLink* link;

@property(nonatomic) NSString* name;

@property(nonatomic) NSObject* value;

@end
