#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPEmailProperties.h"
#import "ASPLink.h"
#import "ASPStream.h"


@protocol ASPEmailDocument
@end

@interface ASPEmailDocument : ASPObject


@property(nonatomic) NSArray<ASPLink>* links;

@property(nonatomic) ASPEmailProperties* documentProperties;

@property(nonatomic) ASPStream* data;

@property(nonatomic) NSString* format;

@end
