#!/usr/bin/env python

class EmailProperties(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Link': 'Link',
            'List': 'list[EmailProperty]'

        }

        self.attributeMap = {
            'Link': 'Link','List': 'List'}       

        self.Link = None # Link
        self.List = None # list[EmailProperty]
        
