#!/usr/bin/env python

class EmailPropertyResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'EmailProperty': 'EmailProperty',
            'Code': 'int',
            'Status': 'str'

        }

        self.attributeMap = {
            'EmailProperty': 'EmailProperty','Code': 'Code','Status': 'Status'}       

        self.EmailProperty = None # EmailProperty
        self.Code = None # str
        self.Status = None # str
        
