#!/usr/bin/env python

class EmailDocument(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Links': 'list[Link]',
            'DocumentProperties': 'EmailProperties',
            'Data': 'str',
            'Format': 'str'

        }

        self.attributeMap = {
            'Links': 'Links','DocumentProperties': 'DocumentProperties','Data': 'Data','Format': 'Format'}       

        self.Links = None # list[Link]
        self.DocumentProperties = None # EmailProperties
        self.Data = None # System.IO.Stream
        self.Format = None # str
        
