<?php
namespace Aspose\Email\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class EmailDocumentResponse {
	static $swaggerTypes = array(
		'Link' => 'Link',
		'Properties' => 'array[EmailProperty]',
		'Document' => 'EmailDocument',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Link; // Link
	public $Properties; // array[EmailProperty]
	public $Document; // EmailDocument
	public $Code; // string
	public $Status; // string
	}

